# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=adit2264
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=adit2264
ENV MYSQL_DATABASE=devtrackdb

# Expose MySQL port
EXPOSE 3306
